### ISSUE TITLE
Clean up temp folder when build fails

### ISSUE THREAD

**Issue by mixspace** [mixspace/lexicon-issues#6]
Lexicon creates a temp folder during the build process to push credentials into a build. Currently, if the build fails this temp folder is not cleaned up. That can result in situations like this:

![image](https://user-images.githubusercontent.com/32339726/39822278-26fb2e2c-5378-11e8-9e1e-26eaa9fbac82.png)

**Comment by rossman22590** [comment]
Assets/Lexicon/Scripts/Watson/Conversation/v1/LexiconConversation.cs(47,111): error CS1061: Type `IBM.Watson.DeveloperCloud.Utilities.Credentials' does not contain a definition for `AuthenticationToken' and no extension method `AuthenticationToken' of type `IBM.Watson.DeveloperCloud.Utilities.Credentials' could be found. Are you missing an assembly reference?

Assets/Lexicon/Scripts/Watson/SpeechToText/v1/LexiconSpeechToText.cs(312,61): error CS1061: Type `IBM.Watson.DeveloperCloud.Utilities.Credentials' does not contain a definition for `HasAuthorizationToken' and no extension method `HasAuthorizationToken' of type `IBM.Watson.DeveloperCloud.Utilities.Credentials' could be found. Are you missing an assembly reference?

Assets/Lexicon/Scripts/Watson/Conversation/v1/LexiconConversation.cs(45,29): error CS1061: Type `IBM.Watson.DeveloperCloud.Utilities.Credentials' does not contain a definition for `HasAuthorizationToken' and no extension method `HasAuthorizationToken' of type `IBM.Watson.DeveloperCloud.Utilities.Credentials' could be found. Are you missing an assembly reference?

**Comment by rossman22590** [comment]
Assets/Lexicon/Scripts/Watson/SpeechToText/v1/LexiconSpeechToText.cs(37,1): error CS0138: A `using' directive can only be applied to namespaces but `IBM.Watson.DeveloperCloud.Utilities.Credentials' denotes a type. Consider using a `using static' instead

**Comment by mixspace** [comment]
@rossman22590 Thanks for the report! Opened a new issue here: https://github.com/mixspace/lexicon-issues/issues/7

**Comment by mixspace** [comment]
Fixed in 0.5.4
